version: '3'
services:
  checkmate-api:
    build:
      context: ./checkmate
      dockerfile: Dockerfile
    volumes:
      - ${CHECKMATE_DATA}:/var/lib/checkmate
      - ${CHECKMATE_PLUGINS}:/app/plugins
    ports:
      - 17283:17283
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 16G
        reservations:
          cpus: '1'
          memory: 2G
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 60s
  checkmate-app:
    build:
      context: ./checkmate-app
      dockerfile: Dockerfile
    depends_on:
      - checkmate-api
    ports:
      - ${CHECKMATE_PORT}:80
    environment:
      - NGINX_PORT=80
      - CHECKMATE_API_PORT=${CHECKMATE_API_PORT:-17283}
      - CHECKMATE_API_HOST=checkmate-api
      - CHECKMATE_APP_SERVERNAME=${CHECKMATE_APP_SERVERNAME:-localhost}
  